/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'aikin' at '2/26/17 4:22 PM' with Gradle 2.12
 *
 * @author aikin, @date 2/26/17 4:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
